/**
 * Server ↔ registry drift check.
 *
 * The backend commits the field names of every v1 write model to
 * `schemas/api_v1_fields.txt` (generated by scripts/dump_api_v1_fields.py).
 * This script diffs that file against the command registry so a field the API
 * accepts but the CLI (and every generated integration) cannot set fails the
 * build — instead of shipping unreachable, which is how three fields went
 * unexposed for a week in July 2026.
 *
 *   npm run fields:check                       # sibling checkout ../cal-bot-new
 *   CARLY_API_FIELDS_FILE=/path/to/api_v1_fields.txt npm run fields:check
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bookingPagesCreateCommand, bookingPagesUpdateCommand } from '../src/commands/booking-pages/index.js';
import { schedulesCreateCommand, schedulesUpdateCommand } from '../src/commands/schedules/index.js';
import type { CommandDefinition } from '../src/core/types.js';

const here = dirname(fileURLToPath(import.meta.url));
const file =
  process.env.CARLY_API_FIELDS_FILE ?? resolve(here, '..', '..', 'cal-bot-new', 'schemas', 'api_v1_fields.txt');

// Server model → the command that posts it, plus fields the registry names
// differently on purpose (CLI key → server key) or deliberately leaves out.
const PAIRS: Array<{
  model: string;
  command: CommandDefinition;
  renamed?: Record<string, string>;
  intentionallyUnexposed?: string[];
}> = [
  { model: 'BookingPageCreateRequest', command: bookingPagesCreateCommand },
  {
    model: 'BookingPageUpdateRequest',
    command: bookingPagesUpdateCommand,
    // The update model's column is `length`; the API also accepts `duration`,
    // which is what the CLI sends on create and update alike.
    renamed: { duration: 'length' },
    // `username` is a profile property the update endpoint ignores; the
    // registry shares the option list with create, where it is real.
    intentionallyUnexposed: [],
  },
  { model: 'ScheduleCreateRequest', command: schedulesCreateCommand },
  { model: 'ScheduleUpdateRequest', command: schedulesUpdateCommand },
];

const snake = (s: string): string => s.replace(/(?<!^)(?=[A-Z])/g, '_').toLowerCase();

function parseArtifact(text: string): Map<string, Set<string>> {
  const models = new Map<string, Set<string>>();
  let current: Set<string> | null = null;
  for (const raw of text.split('\n')) {
    if (!raw.trim() || raw.startsWith('#')) continue;
    if (!raw.startsWith(' ')) {
      current = new Set<string>();
      models.set(raw.trim().split(/\s+/)[0], current);
    } else if (current) {
      current.add(raw.trim());
    }
  }
  return models;
}

if (!existsSync(file)) {
  console.error(`api_v1_fields.txt not found at ${file} — set CARLY_API_FIELDS_FILE`);
  process.exit(2);
}
const server = parseArtifact(readFileSync(file, 'utf8'));
let failed = false;
for (const { model, command, renamed = {}, intentionallyUnexposed = [] } of PAIRS) {
  const expected = server.get(model);
  if (!expected) {
    console.error(`${model}: not in ${file}`);
    failed = true;
    continue;
  }
  const registry = new Set(
    Object.entries(command.fieldMappings)
      .filter(([, where]) => where === 'body')
      .map(([field]) => renamed[field] ?? snake(field)),
  );
  const missing = [...expected].filter((f) => !registry.has(f) && !intentionallyUnexposed.includes(f));
  const unknown = [...registry].filter((f) => !expected.has(f));
  const status = missing.length || unknown.length ? 'DRIFT' : 'ok';
  console.log(`${status.padEnd(5)} ${model} ↔ ${command.name}: server ${expected.size} fields, registry ${registry.size}`);
  for (const f of missing) console.log(`       missing in CLI:   ${f}`);
  for (const f of unknown) console.log(`       unknown to API:   ${f}`);
  if (missing.length || unknown.length) failed = true;
}
process.exit(failed ? 1 : 0);
